import { Product, Category, Banner, FlashSale, Review, Coupon } from '../types/index';

export const MOCK_CATEGORIES: Category[] = [
  { id: 'cat-phones', name_en: 'Smartphones & Tablets', name_bn: 'স্মার্টফোন ও ট্যাব', slug: 'smartphones-tablets', icon: 'Smartphone', is_active: 1, product_count: 8, image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=500&auto=format&fit=crop&q=80' },
  { id: 'cat-gadgets', name_en: 'Electronics & Gadgets', name_bn: 'ইলেকট্রনিক্স ও গ্যাজেট', slug: 'electronics-gadgets', icon: 'Cpu', is_active: 1, product_count: 12, image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&auto=format&fit=crop&q=80' },
  { id: 'cat-men-fashion', name_en: "Men's Fashion", name_bn: 'পুরুষদের ফ্যাশন', slug: 'mens-fashion', icon: 'Shirt', is_active: 1, product_count: 15, image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=500&auto=format&fit=crop&q=80' },
  { id: 'cat-women-fashion', name_en: "Women's Fashion", name_bn: 'নারীদের ফ্যাশন', slug: 'womens-fashion', icon: 'Sparkles', is_active: 1, product_count: 18, image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=500&auto=format&fit=crop&q=80' },
  { id: 'cat-appliances', name_en: 'Home Appliances', name_bn: 'হোম অ্যাপ্লায়েন্সেস', slug: 'home-appliances', icon: 'Tv', is_active: 1, product_count: 6, image: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=500&auto=format&fit=crop&q=80' },
  { id: 'cat-grocery', name_en: 'Grocery & Organic Food', name_bn: 'মুদি ও খাঁটি খাদ্য', slug: 'grocery-food', icon: 'ShoppingBag', is_active: 1, product_count: 10, image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=500&auto=format&fit=crop&q=80' },
  { id: 'cat-watches', name_en: 'Watches & Wearables', name_bn: 'ঘড়ি ও ওয়্যারেবলস', slug: 'watches-wearables', icon: 'Watch', is_active: 1, product_count: 7, image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&auto=format&fit=crop&q=80' },
  { id: 'cat-footwear', name_en: 'Footwear & Bags', name_bn: 'জুতো ও ব্যাগ', slug: 'footwear-bags', icon: 'Footprints', is_active: 1, product_count: 9, image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&auto=format&fit=crop&q=80' },
  { id: 'cat-computers', name_en: 'Computers & Laptops', name_bn: 'কম্পিউটার ও ল্যাপটপ', slug: 'computers-laptops', icon: 'Laptop', is_active: 1, product_count: 5, image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500&auto=format&fit=crop&q=80' },
  { id: 'cat-health-beauty', name_en: 'Health & Beauty', name_bn: 'স্বাস্থ্য ও সৌন্দর্য', slug: 'health-beauty', icon: 'Heart', is_active: 1, product_count: 8, image: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=500&auto=format&fit=crop&q=80' }
];

export const MOCK_BANNERS: Banner[] = [
  {
    id: 'ban-1',
    title_en: 'Grand Eid & Ramadan Mega Festival 2026',
    title_bn: 'ঈদ ও রমজান মেগা সেল ২০২৬',
    subtitle_en: 'Up to 60% OFF on Top Brands + Free Delivery Across 64 Districts',
    subtitle_bn: 'সেরা ব্র্যান্ডে ৬০% পর্যন্ত অবিশ্বাস্য ছাড় ও সারা দেশে ফ্রি হোম ডেলিভারি!',
    image_desktop: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=1600&auto=format&fit=crop&q=80',
    image_mobile: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&auto=format&fit=crop&q=80',
    link_url: '/shop?tag=eid-mega-sale',
    cta_text_en: 'Explore Offers',
    cta_text_bn: 'অফারগুলো দেখুন'
  },
  {
    id: 'ban-2',
    title_en: 'Latest Flagship Smartphones & Smart Wearables',
    title_bn: 'লেটেস্ট স্মার্টফোন ও গ্যাজেট কালেকশন',
    subtitle_en: 'Official 1-Year Brand Warranty with 0% EMI Facility',
    subtitle_bn: '১ বছরের অফিসিয়াল ব্র্যান্ড ওয়ারেন্টি এবং সহজ কিস্তির সুবিধা',
    image_desktop: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=1600&auto=format&fit=crop&q=80',
    image_mobile: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop&q=80',
    link_url: '/shop?category=smartphones-tablets',
    cta_text_en: 'Shop Smartphones',
    cta_text_bn: 'স্মার্টফোন কিনুন'
  },
  {
    id: 'ban-3',
    title_en: 'Authentic Traditional Fashion & Handloom Wear',
    title_bn: 'আভিজাত্যময় খাঁটি দেশীয় জামদানি ও পাঞ্জাবি',
    subtitle_en: 'Pure Handloom Cotton, Tangail Silk & Designer Collection',
    subtitle_bn: 'হাতে বোনা পিওর সুতি, টাঙ্গাইল সিল্ক ও প্রিমিয়াম ডিজাইন কালেকশন',
    image_desktop: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1600&auto=format&fit=crop&q=80',
    image_mobile: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&auto=format&fit=crop&q=80',
    link_url: '/shop?category=mens-fashion',
    cta_text_en: 'Explore Fashion',
    cta_text_bn: 'ফ্যাশন কালেকশন'
  }
];

export const MOCK_FLASH_SALE: FlashSale = {
  id: 'fs-eid-2026',
  title_en: 'Ramadan & Eid Mega Flash Deals 2026',
  title_bn: 'রমজান ও ঈদ মেগা ফ্ল্যাশ ডিল ২০২৬',
  start_time: new Date(Date.now() - 3600000).toISOString(),
  end_time: new Date(Date.now() + 86400000 * 5).toISOString(),
  discount_text: 'Up to 55% OFF'
};

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name_en: 'Walton Smart LED TV 43" 4K Google TV Voice Control',
    name_bn: 'ওয়ালটন স্মার্ট ৪৩ ইঞ্চি ৪কে গুগল ভয়েস কন্ট্রোল টিভি',
    slug: 'walton-smart-led-tv-43-inch-4k',
    sku: 'WLT-TV-43G',
    category_id: 'cat-appliances',
    category_name_en: 'Home Appliances',
    category_name_bn: 'হোম অ্যাপ্লায়েন্সেস',
    brand_name: 'Walton',
    price: 42500,
    sale_price: 36900,
    cost_price: 31000,
    stock_quantity: 24,
    stock_status: 'IN_STOCK',
    is_featured: 1,
    is_flash_sale: 1,
    flash_sale_price: 35500,
    rating: 4.8,
    review_count: 38,
    warranty: '৫ বছরের প্যানেল ওয়ারেন্টি',
    return_policy: '৭ দিনের সহজ রিটার্ন',
    status: 'PUBLISHED',
    description_en: 'Stunning 4K HDR display with Dolby Audio, Google Voice Assistant, Netflix and YouTube pre-installed. Energy efficient certified.',
    description_bn: 'ডলবি অডিও ও গুগল ভয়েস রিমোট সহ ক্রিস্টাল ক্লিয়ার ৪কে এইচডিআর ডিসপ্লে। ৫ বছরের অফিসিয়াল প্যানেল গ্যারান্টি।',
    primary_image: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=800&auto=format&fit=crop&q=80',
    tags: 'tv,walton,4k,electronics',
    created_at: new Date().toISOString()
  },
  {
    id: 'prod-2',
    name_en: 'Xiaomi Redmi Note 13 Pro (8GB RAM / 256GB ROM)',
    name_bn: 'শাওমি রেডমি নোট ১৩ প্রো (৮জিবি / ২৫৬জিবি)',
    slug: 'xiaomi-redmi-note-13-pro-8gb-256gb',
    sku: 'XIA-RN13P-256',
    category_id: 'cat-phones',
    category_name_en: 'Smartphones & Tablets',
    category_name_bn: 'স্মার্টফোন ও ট্যাব',
    brand_name: 'Xiaomi',
    price: 31999,
    sale_price: 28499,
    cost_price: 25000,
    stock_quantity: 45,
    stock_status: 'IN_STOCK',
    is_featured: 1,
    is_flash_sale: 1,
    flash_sale_price: 27999,
    rating: 4.9,
    review_count: 56,
    warranty: '১ বছরের অফিসিয়াল ব্র্যান্ড ওয়ারেন্টি',
    return_policy: '৭ দিনের সহজ রিটার্ন',
    status: 'PUBLISHED',
    description_en: '200MP OIS Camera, 120Hz AMOLED Display, 67W Turbo Charge with 5000mAh long battery life.',
    description_bn: '২০০ মেগাপিক্সেল অপটিক্যাল ইমেজ স্ট্যাবিলাইজার ক্যামেরা, ১২০ হার্টজ অ্যামোলেড ডিসপ্লে ও ৬৭ ওয়াট ফাস্ট চার্জার।',
    primary_image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&auto=format&fit=crop&q=80',
    tags: 'xiaomi,smartphone,mobile,camera',
    created_at: new Date().toISOString()
  },
  {
    id: 'prod-3',
    name_en: 'Aarong Handloom Pure Cotton Semi-Long Panjabi for Men',
    name_bn: 'আড়ং হ্যান্ডলুম পিওর কটন সেমি-লং পাঞ্জাবি',
    slug: 'aarong-handloom-pure-cotton-panjabi-men',
    sku: 'AAR-PANJ-01',
    category_id: 'cat-men-fashion',
    category_name_en: "Men's Fashion",
    category_name_bn: 'পুরুষদের ফ্যাশন',
    brand_name: 'Aarong',
    price: 2950,
    sale_price: 2450,
    stock_quantity: 60,
    stock_status: 'IN_STOCK',
    is_featured: 1,
    is_flash_sale: 0,
    rating: 4.7,
    review_count: 42,
    warranty: '৭ দিনের সহজ এক্সচেঞ্জ গ্যারান্টি',
    status: 'PUBLISHED',
    description_en: 'Comfortable handwoven 100% pure cotton Panjabi featuring delicate embroidery on the collar and placket. Perfect for Eid and celebrations.',
    description_bn: '১০০% খাঁটি সুতি কাপড়ে নিপুণ সূচিকর্মের সেমি-লং পাঞ্জাবি। গরমের দিনে চমৎকার আরামদায়ক ও আভিজাত্যপূর্ণ।',
    primary_image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&auto=format&fit=crop&q=80',
    tags: 'fashion,panjabi,aarong,eid,cotton',
    created_at: new Date().toISOString()
  },
  {
    id: 'prod-4',
    name_en: 'Aarong Traditional Jamdani Motif Soft Silk Saree with Blouse Piece',
    name_bn: 'আড়ং জামদানি মোটিফ সফট সিল্ক শাড়ি',
    slug: 'aarong-jamdani-motif-soft-silk-saree',
    sku: 'AAR-SAR-JAM',
    category_id: 'cat-women-fashion',
    category_name_en: "Women's Fashion",
    category_name_bn: 'নারীদের ফ্যাশন',
    brand_name: 'Aarong',
    price: 6800,
    sale_price: 5490,
    stock_quantity: 18,
    stock_status: 'IN_STOCK',
    is_featured: 1,
    is_flash_sale: 1,
    flash_sale_price: 5200,
    rating: 4.9,
    review_count: 27,
    warranty: '৭ দিনের সহজ রিটার্ন',
    status: 'PUBLISHED',
    description_en: 'Exquisite Jamdani weave patterns on feather-light soft silk. Comes with matched unstitched blouse piece.',
    description_bn: 'কোমল নরম সিল্কের ওপর ঐতিহ্যবাহী জামদানি নকশার অনবদ্য বয়ন। উৎসব ও বিয়েবাড়ির জন্য পারফেক্ট।',
    primary_image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80',
    tags: 'saree,jamdani,aarong,silk,women',
    created_at: new Date().toISOString()
  },
  {
    id: 'prod-5',
    name_en: 'Apex Venturini Genuine Leather Formal Loafers for Men',
    name_bn: 'এপেক্স ভেনচুরিনি জেনুইন লেদার ফর্মাল লোফার সু',
    slug: 'apex-venturini-genuine-leather-formal-loafers',
    sku: 'APX-VNT-09',
    category_id: 'cat-footwear',
    category_name_en: 'Footwear & Bags',
    category_name_bn: 'জুতো ও ব্যাগ',
    brand_name: 'Apex',
    price: 4990,
    sale_price: 4290,
    stock_quantity: 30,
    stock_status: 'IN_STOCK',
    is_featured: 1,
    is_flash_sale: 0,
    rating: 4.6,
    review_count: 19,
    warranty: '৬ মাসের সোল ও পেস্টিং ওয়ারেন্টি',
    status: 'PUBLISHED',
    description_en: 'Handcrafted full-grain genuine leather with padded inner cushion and durable non-slip rubber sole.',
    description_bn: '১০০% খাঁটি লেদারের ক্লাসিক স্লিপ-অন লোফার। ভেতরে নরম ফোম কুশনিং এবং টেকসই রাবার গ্রিপ সোল।',
    primary_image: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=800&auto=format&fit=crop&q=80',
    tags: 'shoes,apex,leather,formal,footwear',
    created_at: new Date().toISOString()
  },
  {
    id: 'prod-6',
    name_en: 'Pure Sundarban Wild Flower Raw Honey (১ কেজি সুন্দরবনের খাঁটি মধু)',
    name_bn: 'সুন্দরবনের ১০০% প্রাকৃতিক বুনো ফুলের খাঁটি মধু (১ কেজি)',
    slug: 'pure-sundarban-wild-flower-raw-honey-1kg',
    sku: 'HON-SUN-1KG',
    category_id: 'cat-grocery',
    category_name_en: 'Grocery & Organic Food',
    category_name_bn: 'মুদি ও খাঁটি খাদ্য',
    price: 1350,
    sale_price: 1150,
    stock_quantity: 75,
    stock_status: 'IN_STOCK',
    is_featured: 1,
    is_flash_sale: 1,
    flash_sale_price: 1050,
    rating: 5.0,
    review_count: 84,
    warranty: '১০০% ভেজালমুক্ত গ্যারান্টি, ল্যাব টেস্টেড',
    status: 'PUBLISHED',
    description_en: '100% Unprocessed, raw wild flower honey harvested ethically from the Sundarbans mangrove forest.',
    description_bn: 'সুন্দরবনের গভীরে মৌয়ালদের হাতে সংগৃহীত প্রাকৃতিক খাঁটি মধু। কোনো কৃত্রিম মিষ্টি বা প্রিজারভেটিভ নেই।',
    primary_image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&auto=format&fit=crop&q=80',
    tags: 'honey,organic,grocery,sundarban',
    created_at: new Date().toISOString()
  },
  {
    id: 'prod-7',
    name_en: 'Casio Edifice Tachymeter Chronograph Stainless Steel Watch',
    name_bn: 'ক্যাসিও এডিফিস স্টেইনলেস স্টিল ক্রোনোগ্রাফ ঘড়ি',
    slug: 'casio-edifice-tachymeter-chronograph-watch',
    sku: 'CAS-EDF-550',
    category_id: 'cat-watches',
    category_name_en: 'Watches & Wearables',
    category_name_bn: 'ঘড়ি ও ওয়্যারেবলস',
    brand_name: 'Casio',
    price: 14500,
    sale_price: 12800,
    stock_quantity: 15,
    stock_status: 'IN_STOCK',
    is_featured: 1,
    is_flash_sale: 0,
    rating: 4.8,
    review_count: 31,
    warranty: '২ বছরের আন্তর্জাতিক ব্যাটারি ও মেকানিজম ওয়ারেন্টি',
    status: 'PUBLISHED',
    description_en: '100m Water Resistance, Tachymeter bezel, Sapphire coated mineral glass, precision quartz movement.',
    description_bn: '১০০ মিটার ওয়াটারপ্রুফ এবং প্রিসিশন ক্রোনোগ্রাফ মেকানিজম সহ প্রিমিয়াম ক্যাসিও এডিফিস ওয়াচ।',
    primary_image: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&auto=format&fit=crop&q=80',
    tags: 'watch,casio,edifice,chronograph',
    created_at: new Date().toISOString()
  },
  {
    id: 'prod-8',
    name_en: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
    name_bn: 'সোনি ওয়্যারলেস অ্যাক্টিভ নয়েজ ক্যানসেলিং হেডফোন',
    slug: 'sony-wh-1000xm5-noise-cancelling-headphones',
    sku: 'SNY-WH-XM5',
    category_id: 'cat-gadgets',
    category_name_en: 'Electronics & Gadgets',
    category_name_bn: 'ইলেকট্রনিক্স ও গ্যাজেট',
    price: 38500,
    sale_price: 34990,
    stock_quantity: 12,
    stock_status: 'IN_STOCK',
    is_featured: 1,
    is_flash_sale: 1,
    flash_sale_price: 33900,
    rating: 4.9,
    review_count: 45,
    warranty: '১ বছরের অফিসিয়াল রিপ্লেসমেন্ট ওয়ারেন্টি',
    status: 'PUBLISHED',
    description_en: 'Industry-leading Active Noise Cancellation with Auto NC Optimizer, 30 hours battery life and crystal clear calls.',
    description_bn: 'বিশ্বখ্যাত অ্যাক্টিভ নয়েজ ক্যান্সেলেশন, হাই-রেজুলুশন অডিও এবং ৩০ ঘণ্টার লং ব্যাটারি ব্যাকআপ।',
    primary_image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
    tags: 'sony,audio,headphones,gadgets',
    created_at: new Date().toISOString()
  }
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    product_id: 'prod-2',
    customer_name: 'তানভীর হাসান',
    rating: 5,
    comment: 'অসাধারণ সার্ভিস! অর্ডার করার ২৪ ঘণ্টার মধ্যেই ধানমন্ডিতে হোম ডেলিভারি পেয়েছি। প্রোডাক্ট ১০০% অরিজিনাল ও ইনট্যাক্ট প্যাক।',
    is_verified_purchase: 1,
    created_at: '২০২৬-০৩-১২'
  },
  {
    id: 'rev-2',
    product_id: 'prod-4',
    customer_name: 'নুসরাত জাহান',
    rating: 5,
    comment: 'জামদানি শাড়িটির ফেব্রিক এবং বুটি কাজের ফিনিশিং চোখে পড়ার মতো সুন্দর। ছবিতে যেমন ছিল হুবহু তেমনই পেয়েছি।',
    is_verified_purchase: 1,
    created_at: '২০২৬-০৩-১০'
  },
  {
    id: 'rev-3',
    product_id: 'prod-6',
    customer_name: 'আব্দুল কাদের',
    rating: 5,
    comment: 'সুন্দরবনের খাঁটি মধু সত্যি অতুলনীয় স্বাদ ও ঘ্রাণ। প্যাকেজিং খুবই নিরাপদ ছিল যাতে বিন্দুমাত্র লিক না করে।',
    is_verified_purchase: 1,
    created_at: '২০২৬-০৩-০৯'
  }
];

export const MOCK_COUPONS: Coupon[] = [
  {
    id: 'cpn-1',
    code: 'GLOBAL10',
    discount_type: 'PERCENTAGE',
    discount_val: 10,
    min_order_val: 1000,
    max_discount: 500,
    used_count: 14,
    is_active: 1
  },
  {
    id: 'cpn-2',
    code: 'RAMADAN2026',
    discount_type: 'PERCENTAGE',
    discount_val: 15,
    min_order_val: 2000,
    max_discount: 1000,
    used_count: 28,
    is_active: 1
  }
];
